name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy, llvm-tools-preview

      - name: Build check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Format check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          RUSTFLAGS: -C instrument-coverage

      - name: Install coverage tool
        run: |
          wget https://github.com/feroldi/grcov/releases/download/v0.8.8-feroldi/grcov.tar.bz2 -O grcov.tar.bz2
          tar -xf grcov.tar.bz2

      - name: Collect coverage statistics
        run: ./grcov default.profraw --source-dir . --binary-path ./target/debug/ --llvm --branch --output-type html --output-path ./coverage

      - name: Publish coverage statistics
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_ACCESS_TOKEN }}
        with:
          source-directory: 'coverage'
          destination-github-username: 'feroldi'
          destination-repository-name: 'atlas-coverage'
          target-branch: master
