name: ci

on:
  push:
    branches: [ main ]
    paths-ignore: [ '**.md' ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build files cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-v1-${{ hashFiles('**/Cargo.lock') }}

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: llvm-tools-preview

      - name: Run tests with coverage
        uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          CARGO_TERM_COLOR: always
          RUSTFLAGS: -C instrument-coverage
          LLVM_PROFILE_FILE: coverage-%p-%m.profraw

      - name: Install coverage tool
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: grcov --version 0.8.9

      - name: Collect coverage statistics
        run: ./grcov . --source-dir . --binary-path ./target/debug/ --llvm --branch --output-type html --output-path ./coverage
        id: grcov

      - name: Publish coverage statistics
        if: steps.grcov.conclusion == 'success'
        uses: cpina/github-action-push-to-another-repository@v1.4.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_ACCESS_TOKEN }}
        with:
          source-directory: 'coverage'
          destination-github-username: 'feroldi'
          destination-repository-name: 'atlas-coverage'
          target-branch: master
